export const UI_TEXT = {
  appName: 'Happy Lines',
  splashTitle: 'Happy Lines',
  splashSubtitle: 'Deine naechste Malvorlage entsteht gerade.',
  splashLoading: 'Malsachen werden vorbereitet...',
  hubTitle: 'Was moechtest du heute gestalten?',
  hubSubtitle: 'Starte mit einer Idee oder verwandle ein eigenes Bild in eine Malvorlage.',
  createCardTitle: 'Idee erstellen',
  createCardSubtitle: 'Neue Malvorlage aus deiner Idee entwickeln',
  uploadCardTitle: 'Bild hochladen',
  uploadCardSubtitle: 'Eigenes Bild hochladen und in Zahlen verwandeln',
  ideaScreenTitle: 'Welche Idee hast du?',
  ideaScreenSubtitle: 'Beschreibe dein Motiv, wir machen daraus erst ein Bild und danach deine Malvorlage.',
  configTitle: 'Fast fertig',
  configSubtitle: 'Lege noch Stil und Detailgrad fest, dann starten wir die Verarbeitung.',
  processingTitle: 'Deine Vorlage entsteht',
  resultTitle: 'Deine Malvorlage ist bereit',
  resultSubtitle: 'Das generierte Bild wurde bereits in eine Paint-by-Numbers-Vorlage umgewandelt.',
};
