export type PosterizePromptInput = {
  colorCount: number;
  complexityLabel: string;
  complexityGuidance: string;
  maxEdge: number;
};

export function buildPaintByNumbersPosterizePrompt(input: PosterizePromptInput): string {
  return [
    'Convert the attached image into a strict paint-by-numbers style illustration.',
    '',
    `Preserve the original composition, proportions, layout, and important subject silhouettes of the source image. Keep the image clearly recognizable, but simplify it into a posterized ${input.complexityLabel.toLowerCase()} interpretation.`,
    '',
    'Color-driven detail target:',
    `- ${input.complexityGuidance}`,
    `- The selected difficulty is controlled by the ${input.colorCount}-color palette. Use this color budget as the main detail control.`,
    '- Prefer a design that naturally fits the selected color budget by simplifying or enriching the motif itself, not by flooding unrelated areas together.',
    '- For lower color counts, omit minor internal details, combine repeated texture into broader semantic zones, simplify small markings, and use larger iconic shapes.',
    '- For higher color counts, preserve more meaningful internal forms, characteristic accents, layered shape boundaries, and subject-defining details while keeping every region clean and flat.',
    '- If the source is very detailed, redraw it as a cleaner, simpler version of the same motif at the same position and scale. For example, a highly detailed object should become a broader, clearer object with fewer internal zones, not a blurred or melted version.',
    '- Do not simplify by merging important subjects into the background, by letting background colors intrude into subject silhouettes, or by destroying the identity of the photographed motif.',
    '',
    'Create a simplified, posterized paint-by-numbers image using closed color regions. Group similar tones together, reduce unnecessary details, and replace realistic shading with discrete, layered tonal zones. Favor readable paintable shapes over fine detail.',
    '',
    'Palette requirement:',
    `- Use exactly ${input.colorCount} flat colors in the final image.`,
    `- Use all ${input.colorCount} colors intentionally; do not collapse the image down to noticeably fewer colors.`,
    '- Use one limited palette only.',
    '- Allocate the limited palette across the main distinct hue families and important accent colors in the image, not only across the largest background areas.',
    '- If the palette is tight, combine similar background tones, repeated texture tones, and minor shading variations before losing small but recognizable accent colors or identity-defining color marks.',
    '- Avoid spending many separate palette slots on subtle variations of the same background hue when another clearly different foreground or subject color would disappear.',
    '- Separate neighboring tones into clearly defined regions instead of blending them.',
    '- Neighboring important objects or foreground/background areas should not use nearly identical colors along critical edges.',
    '',
    'Critical flat-color requirement:',
    '- Render the image as if it were a vector segmentation map for a paint-by-numbers kit.',
    '- Every enclosed shape must be a solid flat-color cell with exactly one uniform RGB color value.',
    '- Inside each color region, there must be no gradient, no texture, no brush grain, no mottling, no noise, no feathering, no transparency, no anti-aliased color drift, and no internal variation of any kind.',
    '- One region = one perfectly uniform color.',
    '',
    'Boundary requirement:',
    '- Boundaries between regions should be clean, crisp, and clearly readable.',
    '- Boundaries may remain slightly organic in contour so the result does not feel mechanically rigid.',
    '- Preserve every important subject silhouette as a closed, readable shape separated from surrounding areas.',
    '- Keep important semantic boundaries intact: foreground versus background, separate objects, overlapping forms, major structural parts, material changes, and identity-defining features.',
    '- Use sufficiently distinct neighboring colors or a narrow separating color region where needed so important subjects never visually melt into the background or into unrelated objects.',
    '- For simpler outputs, remove internal detail first; do not sacrifice outer silhouettes, important object boundaries, or foreground/background separation.',
    '',
    'Visual style:',
    '- Flat acrylic / gouache-inspired paint-by-numbers aesthetic.',
    '- Matte finish.',
    '- Simplified forms.',
    '- Clean posterized shape design.',
    '- Decorative wall-art quality.',
    '- The result should feel hand-composed in design, but technically flat-filled like vector art.',
    '',
    'Important constraints:',
    '- Do not add numbers.',
    '- Do not add labels.',
    '- Do not add text.',
    '- Do not add logos or watermarks.',
    '- Do not add outlines everywhere unless needed for shape separation.',
    '- Do not use gradients.',
    '- Do not use painterly texture.',
    '- Do not use visible brush strokes inside regions.',
    '- Do not use realistic lighting or photorealistic shading.',
    '- Do not create tiny speckled patches or micro-fragments.',
    '- Do not blend colors.',
    '- Do not merge background regions into important subjects.',
    '- Do not let important subjects share nearly identical adjacent colors with the background along important edges.',
    '- Do not change the original composition, camera framing, or relative placement of major elements.',
    '',
    'Output constraint:',
    '- Output a normal clean image only, not a numbered template.',
    `- Keep the useful image size within about ${input.maxEdge}px on the longest edge.`,
    '',
    'Final goal:',
    'A clean, highly readable paint-by-numbers illustration where every distinct color area is a single solid uniform color region, with clearly separated shapes, protected subject silhouettes, and no internal color variation.',
  ].join('\n');
}
